"""add status column to message table

Revision ID: 2c2b1ca522f6
Revises: 3a9baec61c86
Create Date: 2023-03-04 14:07:40.820848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2b1ca522f6'
down_revision = '3a9baec61c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'status')
    # ### end Alembic commands ###
