"""add chat_title column to message table

Revision ID: 55e7e9db8c57
Revises: 2c2b1ca522f6
Create Date: 2023-03-04 16:57:41.443020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e7e9db8c57'
down_revision = '2c2b1ca522f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('chat_title', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'chat_title')
    # ### end Alembic commands ###
