"""add chat_id column to message table

Revision ID: 77f5f7b409c4
Revises: 
Create Date: 2023-03-03 13:29:05.359241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f5f7b409c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('chat_id', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'chat_id')
    # ### end Alembic commands ###
